name: Run Tests on PR # I only made this different in this yml file
on: pull_request # I only made this different in this yml file
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/puppeteer@v2.0.0
      - name: Install NPM Deps
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: npm i
      - name: Test
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: npm test
